### ISSUE TITLE
Add data_output.csv for CCS workflows

### ISSUE THREAD

**Issue by ayang-pacbio** [dalexander/bauhaus#1]
Can you please add a csv file that contains your CCS data outputs please?  This should be what you used to generate plots.  I would like csv file created in case I need to re-plot or do further analysis.

Thank you!
Alicia

**Comment by dalexander** [comment]
I think I fixed this by outputting a "feather" file for you

**Comment by ayang-pacbio** [comment]
Yes, you did.  And it works.

Sent from my iPhone

On Aug 30, 2016, at 11:38 AM, David Alexander <notifications@github.com<mailto:notifications@github.com>> wrote:

I think I fixed this by outputting a "feather" file for you

##
